#include <ft2build.h>
#include FT_FREETYPE_H
#include FT_OUTLINE_H
#include FT_SIZES_H
#include FT_RENDER_H
#include FT_GLYPH_H
#include FT_BITMAP_H
#include FT_BBOX_H
#include FT_CACHE_H
#include FT_STROKER_H
#include FT_SYNTHESIS_H
#include FT_TRIGONOMETRY_H
#include FT_GASP_H
#include FT_ADVANCES_H
#include FT_MULTIPLE_MASTERS_H
#include FT_SFNT_NAMES_H
